import { Product } from '@/types/product';
import { MedicalStore } from '@/types/store';

export const DEMO_STORES: MedicalStore[] = [
  {
    id: 's1',
    name: 'Apollo Pharmacy — Connaught Place',
    drugLicenseNumber: 'DL-DLH-2024-88912',
    rating: 4.9,
    totalRatings: 1240,
    distanceKm: 1.2,
    estimatedDeliveryMinutes: 25,
    isOpen: true,
    operatingHours: { open: '08:00 AM', close: '11:00 PM' },
    address: 'Inner Circle, Connaught Place',
    city: 'New Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&h=400&fit=crop',
    isVerified: true,
    featuredCategories: ['Medicines', 'Wellness', 'Baby Care'],
  },
  {
    id: 's2',
    name: 'MedPlus Chemist & Superstore',
    drugLicenseNumber: 'DL-DLH-2023-45210',
    rating: 4.8,
    totalRatings: 860,
    distanceKm: 2.4,
    estimatedDeliveryMinutes: 30,
    isOpen: true,
    operatingHours: { open: '07:30 AM', close: '10:30 PM' },
    address: 'Kailash Colony Main Market',
    city: 'New Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=600&h=400&fit=crop',
    isVerified: true,
    featuredCategories: ['Medical Devices', 'First Aid', 'Personal Care'],
  },
  {
    id: 's3',
    name: 'Guardian Health Pharmacy',
    drugLicenseNumber: 'DL-DLH-2024-11045',
    rating: 4.7,
    totalRatings: 520,
    distanceKm: 3.1,
    estimatedDeliveryMinutes: 35,
    isOpen: true,
    operatingHours: { open: '24 Hours', close: '24 Hours', isOpen24Hours: true },
    address: 'Defense Colony Flyover Market',
    city: 'New Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop',
    isVerified: true,
    featuredCategories: ['Medicines', 'Personal Care', 'Wellness'],
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'p1',
    storeId: 's1',
    storeName: 'Apollo Pharmacy — Connaught Place',
    name: 'Paracetamol 650mg (Dolo 650)',
    genericName: 'Paracetamol',
    brand: 'Micro Labs',
    category: 'Medicines',
    price: 30,
    mrp: 34,
    discountPercentage: 12,
    prescriptionRequirement: 'NOT_REQUIRED',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    description: 'Effective fever reducer and mild pain reliever for flu symptoms.',
    packSize: '15 Tablets Strip',
    inStock: true,
    stockQuantity: 120,
    rating: 4.8,
    reviewCount: 340,
  },
  {
    id: 'p2',
    storeId: 's2',
    storeName: 'MedPlus Chemist & Superstore',
    name: 'Omeprazole 20mg Antacid Capsules',
    genericName: 'Omeprazole',
    brand: 'Dr. Reddy Labs',
    category: 'Medicines',
    price: 85,
    mrp: 102,
    discountPercentage: 16,
    prescriptionRequirement: 'OPTIONAL',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edf7928d10f8?w=400&h=400&fit=crop',
    description: 'Relieves hyperacidity, acid reflux, and heartburn.',
    packSize: '14 Capsules Box',
    inStock: true,
    stockQuantity: 80,
    rating: 4.7,
    reviewCount: 190,
  },
  {
    id: 'p3',
    storeId: 's1',
    storeName: 'Apollo Pharmacy — Connaught Place',
    name: 'Amoxicillin 500mg Antibiotic',
    genericName: 'Amoxicillin',
    brand: 'Cipla',
    category: 'Medicines',
    price: 110,
    mrp: 135,
    discountPercentage: 18,
    prescriptionRequirement: 'REQUIRED',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
    description: 'Broad-spectrum penicillin antibiotic for bacterial infections.',
    packSize: '10 Capsules Strip',
    inStock: true,
    stockQuantity: 45,
    rating: 4.9,
    reviewCount: 185,
  },
  {
    id: 'p4',
    storeId: 's2',
    storeName: 'MedPlus Chemist & Superstore',
    name: 'Digital Fingertip Pulse Oximeter',
    genericName: 'Pulse Oximeter',
    brand: 'Dr. Trust',
    category: 'Medical Devices',
    price: 1299,
    mrp: 1999,
    discountPercentage: 35,
    prescriptionRequirement: 'NOT_REQUIRED',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
    description: 'Accurate SpO2 pulse monitor with OLED color display.',
    packSize: '1 Unit',
    inStock: true,
    stockQuantity: 25,
    rating: 4.9,
    reviewCount: 512,
  },
];
